[Interface]
Address = 10.77.0.1/24
ListenPort = 51820
PrivateKey = cOe5pnc0vLZGqtP4nITDPjFgj5GH4VYRbZfKVeZe7M4=

[Peer]
PublicKey = aK+Rkq8L/EE7yyKgZ0641gkiwePDZzyssDekLkgCfDE=
AllowedIPs = 10.77.0.2/32

